### ISSUE TITLE
Fix github.io site URL in the description

### ISSUE THREAD

**Issue by veeven** [CashlessConsumer/CashlessConsumer#30]
The URL in the repository description [http://srikanthlogic.github.io/cashlessconsumer](http://srikanthlogic.github.io/cashlessconsumer) throws 404 error. 

Make it: [http://srikanthlogic.github.io/**CashlessConsumer**](http://srikanthlogic.github.io/CashlessConsumer)

TIL: GitHub pages URLs are case-sensitive.

**Comment by srikanthlogic** [comment]
Fixed
