### ISSUE TITLE
Can we implement UPI deeplink to a website?

### ISSUE THREAD

**Issue by Bhavya2118** [CashlessConsumer/CashlessConsumer#44]
Hello sir,
I know invoking a UPI app from a deeplink placed in a website is not an issue, but, can the Web site receive the payment status (successful/failed/submitted) response from the UPI app? It works between two native app, but will it work between one Website and a UPI app?

**Comment by srikanthlogic** [comment]
Refer page 12 of [Latest publicly availble UPI Deeplinking specification](https://www.npci.org.in/sites/default/files/UPI%20Linking%20Specs_ver%201.6.pdf). For more details, please check with your partner PSP / bank.
